version: "3.8"

services:

  api:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - ./config_env/.env
    ports:
      - "8000:80"

  db:
    image: postgres:15.1-alpine
    restart: always
    container_name: database
    env_file:
      - ./config_env/.env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0.12-alpine
    container_name: redis
    env_file:
      - ./config_env/.env
    ports:
      - "6379:6379"
