version: "3"

services:

  api:
    depends_on:
      db:
        condition: service_healthy
    build: .
    container_name: api
    env_file:
      - ./config_env/.env
    ports:
      - "8000:80"

  db:
    image: postgres
    restart: always
    container_name: database
    env_file:
      - ./config_env/.env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5


